import Head from "next/head";
import LogIn from "./Menu/LogIn";

export default function Home() {
  return (
    <div className="max-w-3xl mx-auto">
        <Head>
          <title>Smile House Cafe</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <LogIn />
    </div>
  );
}
